name: ml-client

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      APP_NAME: ${{ secrets.APP_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
      - name: Lint ML client
        run: |
          pipenv run pylint machine_learning_client/**/*.py
      - name: Format check ML client
        run: |
          pipenv run black --check machine_learning_client
      - name: Test ML client
        run: |
          pipenv run pytest machine_learning_client/tests
